version: '3'

services:
  app:
    build: .
    command: -c /fluentd/etc/s3.conf -v -vv
    volumes:
      - ./fluentd:/fluentd/log
      - ./s3.conf:/fluentd/etc/s3.conf:ro

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - ./minio:/data
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/test-bucket;
      /usr/bin/mc policy download myminio/mybucket;
      exit 0;
      "
